support/scripts/check-bin-arch: assumes None as good architecture
Fixes:

	ERROR: architecture for "/usr/lib/guile/2.2/site-ccache/gnutls.go" is "None", should be "Advanced Micro Devices X86-64"
	ERROR: architecture for "/usr/lib/guile/2.2/site-ccache/gnutls/extra.go" is "None", should be "Advanced Micro Devices X86-64"

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>