package/qt5webengine: add missing opus dependency
The package opus is selected but it is not listed in the dependencies.

This adds opus to QT5WEBENGINE_DEPENDENCIES.

Fixes:

	$ make qt5webengine
	(...)
	ERROR: Feature 'webengine-system-opus' was enabled, but the pre-condition 'config.unix && libs.webengine-opus' failed.

Signed-off-by: Gaël PORTAY <gael.portay+rtone@gmail.com>