qt5webkit: fix installation of headers
Since Qt 5.11, the headers are not installed anymore.

The issue comes from a update in qt5base [1] which is not backported to
qt5webkit because it is not officially supported anymore by Qt.

Fixes build issues with qt5webkit-examples that requires QtWebKit
headers:

	In file included from main.cpp:42:
	window.h:46:10: fatal error: QWebElement: No such file or directory
	 #include <QWebElement>
	          ^~~~~~~~~~~~~
	compilation terminated.

[1]: https://github.com/qt/qtbase/commit/9c4c136bc9f29bab1cc9684dfced55a92a8bbe96

Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>